#############################################
# CI WORKFLOW DISABLED (2025-09-30)
# Original file backed up at:
#   docs/workflow_backups/ci.yml.bak
# This placeholder intentionally has only a
# manual dispatch trigger and no jobs.
# To restore CI, move the backup file back to:
#   .github/workflows/ci.yml
#############################################

name: CI (disabled)

on:
  workflow_dispatch:
    inputs:
      note:
        description: "Placeholder – restore backup to re-enable full CI"
        required: false
        default: ""

jobs:
  noop:
    runs-on: ubuntu-latest
    if: ${{ false }}  # always skip
    steps:
      - name: Disabled placeholder
        run: echo "CI disabled. Restore backup to re-enable."
