




[theme]
base = "dark"
primaryColor = "#00B4D8"
backgroundColor = "#18191A"
secondaryBackgroundColor = "#242526"
textColor = "#F5F6FA"
font = "sans serif"

[client]
showSidebarNavigation = true
showErrorDetails = true


[server]
headless = true
fileWatcherType = "auto"

# Symmetric key used to produce signed cookies. If deploying on multiple replicas, this should be set to the same value across all replicas to ensure they all validate cookies identically
cookieSecret = "a-random-key-appears-here"

# If false, will attempt to open a new tab or window when the user clicks on a URL
enableCORS = false

# Enables support for Cross-Site Request Forgery (XSRF) protection, which is highly recommended for production deployments
enableXsrfProtection = true

# Max size, in megabytes, for files uploaded with the file_uploader
maxUploadSize = 200

# Max size, in megabytes, of messages that can be sent via the WebSocket connection
maxMessageSize = 200

# Enables support for websocket compression
enableWebsocketCompression = false

[browser]

# Internet address where users should point their browsers in order to connect to the app
serverAddress = "0.0.0.0"

# Whether to send usage statistics to Streamlit
gatherUsageStats = false

# Port where users should point their browsers in order to connect to the app
serverPort = 8501
